# Generated by Django 5.0.6 on 2025-03-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthdate', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('looking_for', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('age_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
