# Generated by Django 5.0.6 on 2025-03-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0002_alter_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
