# Generated by Django 5.0.6 on 2025-03-13 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0003_alter_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_inscrit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
