# Generated by Django 5.0.6 on 2025-03-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0004_member_date_inscrit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pseudo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(max_length=10)),
                ('cheveux', models.CharField(choices=[('blond', 'Blond'), ('gris', 'Gris'), ('marron', 'Marron'), ('noir', 'Noir'), ('change', 'Je change souvent'), ('chatain', 'Châtain'), ('autre', 'Autre')], max_length=20)),
                ('yeux', models.CharField(max_length=20)),
                ('taille', models.IntegerField()),
                ('poids', models.IntegerField()),
                ('alcool', models.CharField(max_length=20)),
                ('tabac', models.CharField(max_length=20)),
                ('situation', models.CharField(max_length=20)),
                ('enfants', models.IntegerField()),
                ('description', models.TextField()),
                ('recherche', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(upload_to='', verbose_name='static/images/membres/')),
                ('est_valide', models.BooleanField(default=False)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_membres.member')),
            ],
        ),
    ]

    
