# Generated by Django 5.0.6 on 2025-03-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0005_alter_member_pseudo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pseudo',
            field=models.CharField(max_length=100),
        ),
    ]
