# Generated by Django 5.0.6 on 2025-03-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0007_alter_member_pseudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='est_valide',
            new_name='valider',
        ),
    ]
