# Generated by Django 5.0.6 on 2025-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0008_rename_est_valide_profil_valider'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activiter_dernier',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
