# Generated by Django 5.0.6 on 2025-03-24 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0011_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_disliked', models.DateTimeField(auto_now_add=True)),
                ('disliked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_received', to='app_membres.member')),
                ('disliker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_given', to='app_membres.member')),
            ],
            options={
                'unique_together': {('disliker', 'disliked')},
            },
        ),
    ]
