# Generated by Django 5.0.6 on 2025-03-24 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0013_heart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicite', models.CharField(blank=True, max_length=100, null=True)),
                ('art_corporel', models.CharField(blank=True, max_length=100, null=True)),
                ('enfants_souhaites', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('situation_vie', models.CharField(blank=True, max_length=100, null=True)),
                ('demenagement', models.CharField(blank=True, max_length=100, null=True)),
                ('relation_recherche', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau_etude', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('signe_astrologique', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='static/images/membres/')),
                ('additional_image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='static/images/membres/')),
                ('additional_image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='static/images/membres/')),
                ('additional_image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='static/images/membres/')),
                ('additional_image5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='static/images/membres/')),
                ('additional_image6', models.ImageField(blank=True, null=True, upload_to='', verbose_name='static/images/membres/')),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_membres.member')),
            ],
        ),
    ]
