# Generated by Django 5.0.6 on 2025-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0015_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='images',
            field=models.ImageField(upload_to='static/images/profils/'),
        ),
    ]
