# Generated by Django 5.0.6 on 2025-04-08 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0016_alter_profil_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='membre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_membres.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app_membres.member'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='membre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_membres.member'),
        ),
    ]
