# Generated by Django 5.0.6 on 2025-04-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0021_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='validation_generale',
            field=models.BooleanField(default=False),
        ),
    ]
