# Generated by Django 5.0.6 on 2025-04-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0022_profil_validation_generale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='validation_generale',
        ),
    ]
