# Generated by Django 5.0.6 on 2025-04-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0023_remove_profil_validation_generale'),
    ]

    operations = [
        migrations.CreateModel(
            name='validation_automatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorisation', models.BooleanField(default=False)),
            ],
        ),
    ]
