# Generated by Django 5.0.6 on 2025-04-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0024_validation_automatique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validation_automatique',
            options={'verbose_name': 'Validation Automatique', 'verbose_name_plural': 'Validations Automatiques'},
        ),
        migrations.AddField(
            model_name='validation_automatique',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
