# Generated by Django 5.0.6 on 2025-04-19 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0025_alter_validation_automatique_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visitors', to='app_membres.member')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visits', to='app_membres.member')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('visitor', 'visited')},
            },
        ),
    ]
