# Generated by Django 5.0.6 on 2025-04-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0026_profilevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
