# Generated by Django 5.0.6 on 2025-05-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0027_member_reset_token_member_reset_token_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age_debut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='age_fin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
