# Generated by Django 5.0.6 on 2025-05-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0028_member_age_debut_member_age_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/membres/'),
        ),
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/membres/'),
        ),
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/membres/'),
        ),
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/membres/'),
        ),
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/membres/'),
        ),
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/membres/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='images',
            field=models.ImageField(upload_to='images/profils/'),
        ),
    ]
