# Generated by Django 5.0.6 on 2025-05-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0030_alter_additionalprofileinfo_additional_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lieux',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
