# Generated by Django 5.0.6 on 2025-05-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0031_member_lieux'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='desactivation',
            field=models.BooleanField(default=False),
        ),
    ]
