# Generated by Django 5.0.6 on 2025-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0032_member_desactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='blocked_members',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='app_membres.member'),
        ),
    ]
