# Generated by Django 5.2 on 2025-07-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0034_profilnonvalide_profilvalide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='images',
            field=models.ImageField(upload_to='public_html/static/images/profils/'),
        ),
    ]
