# Generated by Django 5.2 on 2025-07-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0036_alter_profil_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='images',
            field=models.ImageField(upload_to='./public_html/static/images/profils/'),
        ),
    ]
