# Generated by Django 5.2 on 2025-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0038_alter_profil_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='images/membres'),
        ),
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='images/membres'),
        ),
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='images/membres/'),
        ),
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='images/membres/'),
        ),
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='images/membres/'),
        ),
        migrations.AlterField(
            model_name='additionalprofileinfo',
            name='additional_image6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='images/membres/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='images',
            field=models.ImageField(upload_to='static/images/profils/'),
        ),
    ]
