# Generated by Django 5.2.3 on 2025-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0041_alter_additionalprofileinfo_additional_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='images',
            field=models.ImageField(upload_to='profils/'),
        ),
    ]
