# Generated by Django 5.2.3 on 2025-08-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_activation_inscription', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activation_btn',
        ),
    ]
