# Generated by Django 5.0.6 on 2025-04-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0016_alter_profil_images'),
        ('app_messages', '0002_message_image_alter_message_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='static/images/validation_messages')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('valider', models.BooleanField(default=False)),
                ('membre_nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_membres.member')),
            ],
        ),
    ]
