# Generated by Django 5.0.6 on 2025-04-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0016_alter_profil_images'),
        ('app_messages', '0003_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='membre_nom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_membres.member'),
        ),
    ]
