# Generated by Django 5.0.6 on 2025-04-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0017_alter_additionalprofileinfo_membre_alter_member_user_and_more'),
        ('app_messages', '0005_alter_photo_membre_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app_membres.member'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app_membres.member'),
        ),
    ]
