# Generated by Django 5.0.6 on 2025-04-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0007_friendrequest_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
