# Generated by Django 5.0.6 on 2025-05-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0009_message_is_read_alter_message_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
