# Generated by Django 5.0.6 on 2025-05-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membres', '0027_member_reset_token_member_reset_token_created'),
        ('app_messages', '0011_alter_message_options_remove_message_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages', to='app_membres.member'),
        ),
    ]
